[versions]
andrroidXCoreKtx="1.12.0"
androidGradlePlugin="8.3.0"
[libraries]
andrroidXCoreKtx={group="androidx.core",name="core-ktx", version.ref="andrroidXCoreKtx"}

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
